### ISSUE TITLE
arrays with enum constraint

### ISSUE THREAD

**Issue by lvivier** [mschema/mschema#12]
It would be useful to have arrays of strings be subject to constraints, but this doesn't work. Worse, it fails in an unhelpful way:

```js
var schema = {
  ports: {
    "type": ["string"],
    "enum": ["usb", "vga", "displayport", "firewire"]
  }
}

var obj = {
  ports: ["usb", "displayport"]
}

mschema.validate(obj, schema)
// -> TypeError: Cannot read property 'length' of undefined
//       at _parse (index.js:238:26)
```

Is there another way to specify that an array should contain only allowed values in mschema?

**Comment by Marak** [comment]
The syntax you are trying to use isn't supported. If you think about the problem it's actually simpler.

Instead of trying to make a custom array type with enums, you could try making a custom string type and use that as the type in a typed array.

```js

var mschema = require('../');

var port = {
  "type": "string",
  "enum": ["usb", "vga", "displayport", "firewire"]
}

var schema = {
  ports: [port]
};

var obj = {
  ports: ["usb", "displayport"]
}

var re = mschema.validate(obj, schema);

console.log(re);

```
Tests for this can be found here: https://github.com/mschema/mschema/blob/master/test/array-typed-as-object-literal-test.js

Let me know if that works for you.

**Comment by lvivier** [comment]
@Marak love it! I think that'll work fine. Thanks for taking the time to explain it.
